modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "immersiveforests"
version = "${version}"
displayName = "ImmersiveForests"
authors = "Kall"
description = '''
'''
#logoFile = ""

[[dependencies.immersiveforests]]
modId="duplicationless"
mandatory=true
versionRange="[1.1.5,)"
ordering="NONE"
side="BOTH"